/**********************************************************************
 * Extern for flatpickr
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var flatpickr = {
  "compareDates": function () { },
  "defaultConfig": {},
  "formatDate": function () { },
  "l10ns": {
    "default": {
      "amPM": {},
      "daysInMonth": {},
      "firstDayOfWeek": {},
      "hourAriaLabel": {},
      "minuteAriaLabel": {},
      "months": {
        "longhand": {},
        "shorthand": {}
      },
      "ordinal": function () { },
      "rangeSeparator": {},
      "scrollTitle": {},
      "time_24hr": {},
      "toggleTitle": {},
      "weekAbbreviation": {},
      "weekdays": {
        "longhand": {},
        "shorthand": {}
      },
      "yearAriaLabel": {}
    },
    "en": {
      "amPM": {},
      "daysInMonth": {},
      "firstDayOfWeek": {},
      "hourAriaLabel": {},
      "minuteAriaLabel": {},
      "months": {
        "longhand": {},
        "shorthand": {}
      },
      "ordinal": function () { },
      "rangeSeparator": {},
      "scrollTitle": {},
      "time_24hr": {},
      "toggleTitle": {},
      "weekAbbreviation": {},
      "weekdays": {
        "longhand": {},
        "shorthand": {}
      },
      "yearAriaLabel": {}
    }
  },
  "localize": function () { },
  "parseDate": function () { },
  "setDefaults": function () { }
};
/**********************************************************************
 * End Generated Extern for flatpickr
/**********************************************************************/
